balasjasa/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('koperasi.urls')),
    path('admin', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

koperasi/urls.py
from django.conf.urls import url
from . import views


app_name = 'koperasi'


urlpatterns = [
    url(r'^$', views.index, name='main'),
    url(r'^akun/add/$', views.AkunCreate, name='akun-add'),
    url(r'^akun/(?P<akun_id>[0-9]+)/delete/$', views.hapus_akun, name='hapus-akun'),
    url(r'^akun/(?P<akun_id>[0-9]+)/$', views.detail_akun, name='detail-akun'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^register$', views.register, name='register'),
    url(r'^buat-koperasi$', views.create_koperasi, name='buat-koperasi'),
]

koperasi/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import datetime


class Koperasi(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, verbose_name="nama koperasi")
    badan_hukum = models.CharField(max_length=200, verbose_name="nomor badan hukum")
    telp = models.CharField(max_length=20)
    alamat = models.CharField(max_length=250)
    fax = models.CharField(max_length=50)
    tgl = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return str(self.pk) + " " + self.nama + " " + self.badan_hukum


class Membership(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl_daftar = models.DateField()
    tgl_berakhir = models.DateField()
    masa_aktif = models.IntegerField()
    status = models.BooleanField()

    def __str__(self):
        return " Koperasi: " + self.koperasi.nama + " Tgl daftar: " + str(self.tgl_daftar) + " Tgl berakhir:" + str(self.tgl_berakhir)

# TODO: ManyToMany - Koperasi memiliki banyak AkunPerkiraan


class Login(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)


class AkunPerkiraan(models.Model):
    KATEGORI = (('1', 'Aktiva'), ('2', 'Hutang'), ('3', 'Modal'), ('4', 'Pendapatan'), ('5', 'HPP'), ('6', 'Biaya'))
    SALDO_NORMAL = (('D', 'Debet'), ('K', 'Kredit'))
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    kode_akun = models.CharField(max_length=50)
    saldo_normal = models.CharField(max_length=10, choices=SALDO_NORMAL)
    kategori = models.CharField(max_length=1, choices=KATEGORI)

    def __str__(self):
        return self.kategori + "." + self.kode_akun + " - " + self.nama + " - " + self.koperasi

    def get_absolute_url(self):
        return reverse('koperasi:detail-akun', kwargs={'pk': self.pk})


class Anggota(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    JK = (('L', 'Laki-laki'), ('P', 'Perempuan'))
    no_identitas = models.CharField(max_length=50)
    nama = models.CharField(max_length=250)
    jk = models.CharField(max_length=1, choices=JK)
    tempat_lahir = models.CharField(max_length=100, verbose_name='tempat lahir')
    tgl_lahir = models.DateField(verbose_name='tanggal lahir')
    alamat = models.CharField(max_length=300)
    pekerjaan = models.CharField(max_length=100)
    jabatan = models.CharField(max_length=100)
    pic = models.FileField(verbose_name='foto')
    scan_identitas = models.FileField()


class TransaksiSimpan(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl = models.DateTimeField(verbose_name='tanggal')
    jumlah = models.IntegerField()
    keterangan = models.CharField(max_length=200)
    anggota = models.ForeignKey(Anggota, on_delete=models.CASCADE)


class TransaksiPinjam(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl = models.DateTimeField(verbose_name='tanggal')
    jumlah = models.IntegerField()
    keterangan = models.CharField(max_length=200)
    anggota = models.ForeignKey(Anggota, on_delete=models.CASCADE)


class Transaksi(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl = models.DateTimeField(verbose_name='tanggal')
    dari_akun = models.CharField(max_length=100)
    untuk_akun = models.CharField(max_length=100)
    jumlah = models.IntegerField()
    user = models.CharField(max_length=100)

koperasi/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import AkunPerkiraan, Koperasi


class AkunForm(forms.ModelForm):
    attrs = {'class': 'w3-input w3-border'}
    KATEGORI = (('1', 'Aktiva'), ('2', 'Hutang'), ('3', 'Modal'), ('4', 'Pendapatan'), ('5', 'HPP'), ('6', 'Biaya'))
    SALDO_NORMAL = (('D', 'Debet'), ('K', 'Kredit'))
    attr = attrs
    attr['required'] = True
    attr['autofocus'] = 'True'
    nama = forms.CharField(widget=forms.TextInput(attr))
    kode_akun = forms.CharField(widget=forms.TextInput(attrs))
    saldo_normal = forms.CharField(widget=forms.Select(attrs, choices=SALDO_NORMAL))
    kategori = forms.CharField(widget=forms.Select(attrs, choices=KATEGORI))

    class Meta:
        model = AkunPerkiraan
        fields = ['nama', 'kode_akun', 'saldo_normal', 'kategori']


class KoperasiForm(forms.ModelForm):
    attrs = {'class': 'w3-input w3-border'}
    nama = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'autofocus': True, 'class': 'w3-input w3-border', }))
    badan_hukum = forms.CharField(widget=forms.TextInput(attrs))
    telp = forms.CharField(widget=forms.TextInput(attrs))
    alamat = forms.CharField(widget=forms.TextInput(attrs))
    fax = forms.CharField(widget=forms.TextInput(attrs))
    tgl = forms.DateTimeField(widget=forms.DateTimeInput(attrs))

    class Meta:
        model = Koperasi
        fields = ['nama', 'badan_hukum', 'telp', 'alamat', 'fax', 'tgl']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

koperasi/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
# from django.views import generic
from .models import AkunPerkiraan, Koperasi, Membership
from .forms import UserForm, AkunForm, KoperasiForm
import datetime
from django.forms import modelformset_factory


def index(request):
    return render(request, 'koperasi/index.html')


def dashboard(request):
    if not request.user.is_authenticated:
        return render(request, 'koperasi/login.html')
    else:
        k = Koperasi.objects.filter(user=request.user)
        context = {
            'all_koperasi': k,
            'all_akun': AkunPerkiraan.objects.filter(koperasi=k),
        }
        return render(request, 'koperasi/dashboard.html', context)


def detail_akun(request, akun_id):
    if not request.user.is_authenticated:
        return render(request, 'koperasi/login.html')
    else:
        akun = get_object_or_404(AkunPerkiraan, pk=akun_id)
        context = {
            'akunperkiraan': akun,
        }
        return render(request, 'koperasi/detail.html', context)


def hapus_akun(request, akun_id):
    if not request.user.is_authenticated:
        return render(request, 'koperasi/login.html')
    else:
        akun = AkunPerkiraan.objects.get(pk=akun_id)
        akun.delete()
        k = Koperasi.objects.filter(user=request.user)
        context = {
            'all_koperasi': k,
            'all_akun': AkunPerkiraan.objects.filter(koperasi=k),
        }
        return render(request, 'koperasi/dashboard.html', context)


def register(request):
    form = UserForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_koperasi = Koperasi.objects.filter(user=request.user)
                return render(request, 'koperasi/dashboard.html', {'all_koperasi': all_koperasi})
    else:
        context = {
            "form": form,
            'error_message': 'Form is not valid'
        }
        return render(request, 'koperasi/register.html', context)

    context = {
        "form": form,
    }
    return render(request, 'koperasi/register.html', context)


def create_koperasi(request):
    KoperasiFormSet = modelformset_factory(Koperasi, form=KoperasiForm, fields='__all__')
    if request.method == 'POST':
        data = {'form-TOTAL_FORMS': '1', 'form-INITIAL_FORMS': '0', 'form-0-tgl': datetime.date.today()}
        form = KoperasiFormSet(request.POST, data)
        if form.is_valid():
            koperasi = form.save(commit=False)
            koperasi.user = request.user
            koperasi.save()
            m = Membership(koperasi=koperasi, tgl_daftar="2018-01-12", tgl_berakhir="2019-11-12", masa_aktif="12", status=True)
            m.save()
            return render(request, 'koperasi/dashboard.html', {'koperasi': koperasi})
    else:
        data = {'form-TOTAL_FORMS': '1', 'form-INITIAL_FORMS': '0', 'form-0-tgl': datetime.date.today(), 'form-0-DELETE': 'on', }
        form = KoperasiFormSet(data, initial=[{'tgl': datetime.date.today()}])
    context = {'form': form}
    return render(request, 'koperasi/create_koperasi.html', context)


def login_user(request):
    # lakukan pengecekan apakah user sudah di autentikasi, jika sudah arahkan ke halaman dashboard, jika belum lakukan pengecekan user
    if request.user.is_authenticated:
        k = Koperasi.objects.filter(user=request.user)
        context = {
            'all_koperasi': k,
            'all_akun': AkunPerkiraan.objects.filter(koperasi=k.first()),
            'user': request.user
        }
        return render(request, 'koperasi/dashboard.html', context)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                k = Koperasi.objects.filter(user=request.user)
                context = {
                    'all_koperasi': k,
                    'all_akun': AkunPerkiraan.objects.filter(koperasi=k.first()),
                    'user': request.user
                }
                return render(request, 'koperasi/dashboard.html', context)
            else:
                return render(request, 'koperasi/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'koperasi/login.html', {'error_message': 'Invalid login'})
    return render(request, 'koperasi/login.html')


def logout_user(request):
    logout(request)  # logout auth user
    form = UserForm(request.POST or None)  # mengambil forms dari daftar form
    context = {
        "form": form,
    }
    return render(request, 'koperasi/login.html', context)


def AkunCreate(request):
    form = AkunForm(request.POST or None)
    if form.is_valid():
        akunperkiraan = form.save(commit=False)
        akunperkiraan.koperasi = Koperasi.objects.get(user=request.user)
        akunperkiraan.save()
        return render(request, 'koperasi/detail.html', {'akunperkiraan': akunperkiraan})
    context = {
        "form": form,
    }
    return render(request, 'koperasi/create_akun.html', context)

koperasi/templates/koperasi/akunperkiraan_form.html
{% extends 'base.html' %}
{% block title %} Tambah Akun Perkiraan{% endblock %}
{% block content %}
<div class="w3-container w3-card">
    <form class="w3-form" action="" method="post">
        {% csrf_token %}
        {% include 'koperasi/form-template.html' %}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

koperasi/templates/koperasi/create_akun.html
{% extends 'base.html' %}
{% block title %} Tambah Akun{% endblock %}
{% block content %}
<form class="w3-container w3-card-4 w3-padding w3-light-grey" action="" method="post">
  <h3>Tambah akun perkiraan</h3>
      {% csrf_token %}
      {% include 'koperasi/form-template.html' %}
      <button type="submit">Submit</button>
</form>
{% endblock %}

koperasi/templates/koperasi/create_koperasi.html
{% extends 'base.html' %}
{% block title %} Data Koperasi{% endblock %}
{% block koperasi_aktive %}w3-blue{% endblock %}
{% block content %}
<form class="w3-container w3-padding" action="" method="post">
  <h3>Daftarkan Koperasi</h3>
    {% csrf_token %}
    {{ form.management_form }}
    {% for forms in form %}
        <div class="w3-container w3-padding">
    		  <label for="id_form-0-nama">Username:</label>
    		  {{forms.nama}}
    	</div>
        <div class="w3-container w3-padding">
    		  <label for="id_form-0-badan_hukum">Badan hukum:</label>
    		  {{forms.badan_hukum}}
    	</div>
        <div class="w3-container w3-padding">
    		  <label for="id_form-0-telp">Telp:</label>
    		  {{forms.telp}}
    	</div>
        <div class="w3-container w3-padding">
    		  <label for="id_form-0-alamat">Alamat:</label>
    		  {{forms.alamat}}
    	</div>
        <div class="w3-container w3-padding">
    		  <label for="id_form-0-fax">Fax:</label>
    		  {{forms.fax}}
    	</div>
        <div class="w3-container w3-padding">
    		  <label for="id_form-0-tgl">Tanggal:</label>
    		  {{forms.tgl}}
    	</div>
    {% endfor %}
    <div class="w3-container w3-padding">
      <button type="submit" class="w3-button w3-green">Submit</button>
  </div>
</form>
{% endblock %}

koperasi/templates/koperasi/dashboard.html
{% extends "base.html" %}
{% block title %} Daftar Koperasi {% endblock %}
{% block koperasi_aktive %}w3-blue{% endblock %}
{% block content %}
<h1>DAFTAR USER</h1>
{% if all_user %}
<ul>
    {% for user in all_user %}
    <li>{{ user.id }} {{ user.username}} {{ user.email}}</li>
    {% endfor %}
</ul>
{% else %}
    <h3>Belum ada user</h3>
{% endif %}

<h3>DAFTAR KOPERASI</h3>
<a href="{% url 'koperasi:buat-koperasi' %}">Buat Koperasi</a>
{% if all_koperasi %}
<ul>
    {% for koperasi in all_koperasi %}
    <li>{{koperasi.nama}}  [{{koperasi.badan_hukum}}] Alamat : {{koperasi.alamat}}</li>
    {% endfor %}
</ul>
{% else %}
	<h3>Anda belum memiliki koperasi</h3>
{% endif%}

<h3>DAFTAR AKUN</h3>
<a href="{% url 'koperasi:akun-add' %}">Tambah Akun</a>
{% if all_akun %}
<ul>
    {% for akun in all_akun %}
        <li>
            <a href="{% url 'koperasi:detail-akun' akun.id %}">
            {{akun.kategori}}.{{akun.kode_akun}} | {{akun.nama}} | {{akun.saldo_normal}}
            </a>
            <a href="{% url 'koperasi:hapus-akun' akun.id %}">Delete</a>
        </li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

koperasi/templates/koperasi/detail.html
{% extends 'base.html' %}
{% block title %} Detail Akun {% endblock %}
{% block content %}
<div class="w3-container w3-card">
    <h3>Detail Akun</h3>
    <p>{{akunperkiraan.kategori}}.{{akunperkiraan.kode_akun}} {{akunperkiraan.nama}}</p>
</div>
{% endblock %}

koperasi/templates/koperasi/form-template.html
<style type="text/css">
    .w3-container input, .w3-container select{
        width: 100%;
    }
</style>

{% for field in form %}
<p>
    <label >{{ field.label_tag }}</label>
    <div class="w3-container">{{field}}{{ field.errors }}</div>
</p>
{% endfor %}

koperasi/templates/koperasi/index.html
{% extends "base_visitor.html" %}
{% load static %}
{% block title %} Daftar Koperasi {% endblock %}
{% block content %}
<!-- First Parallax Image with Logo Text -->
<div class="w3-display-container" style="height:100%;width:100%;" id="head">
  <div id="particle-canvas" class="w3-opacity-min">
  </div>
  <div class="w3-display-middle" style="white-space:nowrap;">
    <span class="w3-center w3-block"><img src="{% static 'images/icon.png' %}" width='300px;'></span>
    <span class="w3-center w3-padding-large w3-black w3-xlarge w3-wide w3-animate-opacity"><span class="w3-hide-small">BALASJASA.ID</span></span>
  </div>
</div>

<!-- register form -->
<div class="w3-padding-64">
</div>

<!-- The App Section -->
<div class="w3-padding-64 w3-white" id="appSection">
  <div class="w3-row-padding">
    <div class="w3-col l8 m6">
      <h1 class="w3-jumbo w3-text-green"><b>Kenapa memilih kami?</b></h1>
      <p>Membangun koperasi yang akuntabel adalah sebuah keharusan. Anda harus membangun koperasi yang akuntabel dan transaparan untuk meningkatkan kepercayaan anggota maupun pihak yang berkepentingan dengan koperasi Anda. Tingkatkan kepercayaan dan daya saing koperasi Anda sekarang juga.</p>
      <button class="w3-button w3-light-grey w3-padding-large w3-section w3-hide-small" onclick="document.getElementById('register').style.display='block'">
        <i class="fa fa-register"></i> Daftar Sekarang
      </button>
      <p><i class="fa fa-chrome w3-large"></i> <i class="fa fa-firefox w3-large"></i> <i class="fa fa-edge w3-large"></i></p>
    </div>
    <div class="w3-col l4 m6">
      <img src="{% static 'images/icon.png' %}" class="w3-image w3-right w3-hide-small" width="335" height="471">
      <div class="w3-center w3-hide-large w3-hide-medium">
        <button class="w3-button w3-block w3-padding-large" onclick="document.getElementById('register').style.display='block'">
          <i class="fa fa-register"></i> Daftar Sekarang
        </button>
        <img src="<?php echo base_url().'assets/icon.png';?>" class="w3-image w3-margin-top" width="335" height="471">
      </div>
    </div>
  </div>
</div>

<!-- Features Section -->
<div class="w3-container w3-padding-64 w3-dark-grey w3-center" id="fitur">
  <h1 class="w3-jumbo"><b>Fitur</b></h1>
  <p>Fitur aplikasi kami.</p>

  <div class="w3-row" style="margin-top:64px">
    <a href="javascript:void(0)" onclick="openFitur('Aman')">
      <div class="w3-col s3">
        <i class="fa fa-user w3-text-orange w3-jumbo" ></i><br>
        <span>Aman</span>
      </div>
    </a>
    <a href="javascript:void(0)" onclick="openFitur('Stabil')">
      <div class="w3-col s3">
        <i class="fa fa-shield w3-text-blue w3-jumbo"></i><br>
        <span>Stabil</span>
      </div>
    </a>
    <a href="javascript:void(0)" onclick="openFitur('Global')">
      <div class="w3-col s3">
        <i class="fa fa-globe w3-text-amber w3-jumbo"></i><br>
        <span>Global</span>
      </div>
    </a>
    <a href="javascript:void(0)" onclick="openFitur('Cloud')">
      <div class="w3-col s3">
        <i class="fa fa-cloud w3-text-blue w3-jumbo"></i><br>
        <span>Cloud</span>
      </div>
    </a>
  </div>
</div>

<!-- fitur show hide -->
<div class="w3-container w3-black w3-center">
<div id="Aman" class="w3-container fitur" style="display:none;">
  <h2>Aman</h2>
  <p>Data anda tetap aman walaupun terjadi bencana.</p>
</div>

<div id="Stabil" class="w3-container fitur" style="display:none">
  <h2>Stabil</h2>
  <p>Akses sistem yang tetap stabil.</p>
</div>

<div id="Global" class="w3-container fitur" style="display:none">
  <h2>Global</h2>
  <p>Global User access</p>
</div>

<div id="Cloud" class="w3-container fitur" style="display:none">
  <h2>Cloud</h2>
  <p>Cloud system make your data keep available</p>
</div>
</div>

<!-- Pricing Section -->
<div class="w3-padding-64 w3-center w3-white" id="harga">
  <h1 class="w3-jumbo"><b>Kalkulasi Harga</b></h1>
  <p class="w3-large">Pilihlah rencana harga yang sesuai dengan kebutuhan Anda.</p>
  <div class="w3-row-padding" style="margin-top:64px">
    <div class="w3-half w3-section">
      <ul class="w3-ul w3-card w3-hover-shadow">
        <li class="w3-dark-grey w3-xlarge w3-padding-32">Standar</li>
        <li class="w3-padding-16"><b>250</b> Photos</li>
        <li class="w3-padding-16"><b>10</b> Features</li>
        <li class="w3-padding-16"><b>No</b> Ads</li>
        <li class="w3-padding-16"><b>Office hours</b> Support</li>
        <li class="w3-padding-16">
          <h2 class="w3-opacity">Rp. 300.000 / bln</h2>
        </li>
        <li class="w3-light-grey w3-padding-24">
          <button class="w3-button w3-black w3-padding-large" onclick="document.getElementById('register').style.display='block'">Daftar</button>
        </li>
      </ul>
    </div>
    <div class="w3-half w3-section">
      <ul class="w3-ul w3-card w3-hover-shadow">
        <li class="w3-red w3-xlarge w3-padding-32">Premium</li>
        <li class="w3-padding-16"><b>1000</b> Photos</li>
        <li class="w3-padding-16"><b>50</b> Features</li>
        <li class="w3-padding-16"><b>No</b> Ads</li>
        <li class="w3-padding-16"><b>Endless</b> Support</li>
        <li class="w3-padding-16">
          <h2 class="w3-opacity">Rp. 500.000 / Bln</h2>
        </li>
        <li class="w3-light-grey w3-padding-24">
          <button class="w3-button w3-black w3-padding-large" onclick="document.getElementById('register').style.display='block'">Daftar</button>
        </li>
      </ul>
    </div>
  </div>
  <br>
</div>

<!-- quote -->
<div id="register" class="w3-modal w3-animate-opacity">
  <div class="w3-container w3-modal-content">
      <i onclick="document.getElementById('register').style.display='none'" class="fa fa-remove w3-xlarge w3-button w3-transparent w3-right w3-xlarge"></i>
<form id="regForm" action="#">
  <!-- One "tab" for each step in the form: -->
  <h1 class="w3-center">Daftar</h1>
  <div class="tab">Data diri Anda
    <p><input placeholder="First name..." oninput="this.className = ''" name="fname"></p>
    <p><input placeholder="Last name..." oninput="this.className = ''" name="lname"></p>
    <p><input placeholder="E-mail..." oninput="this.className = ''" name="email"></p>
    <p><input placeholder="Phone..." oninput="this.className = ''" name="phone"></p>
  </div>
  <div class="tab">Profil Koperasi:
      <p><input placeholder="Nama koperasi..." oninput="this.className = ''" name="nkoperasi"></p>
      <p><input placeholder="Badan hukum..." oninput="this.className = ''" name="bhukum"></p>
      <p><input placeholder="Alamat..." oninput="this.className = ''" name="alamat"></p>
  </div>
  <div class="tab">Login Info:
    <p><input placeholder="Username..." oninput="this.className = ''" name="uname"></p>
    <p><input placeholder="Password..." oninput="this.className = ''" name="pword" type="password"></p>
  </div>
  <div style="overflow:auto;">
    <div style="float:right;">
      <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
      <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
    </div>
  </div>
  <!-- Circles which indicates the steps of the form: -->
  <div style="text-align:center;margin-top:40px;">
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
  </div>
</form>
</div>
</div>
{% endblock %}

koperasi/templates/koperasi/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="{%  static 'images/icon.png' %}"/>
        <link rel="stylesheet" href="{% static 'w3.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <style type="text/css">
        /* Modal Content/Box */
        .login{
            background-color: #ffffff;
            width: 30%; /* Could be more or less, depending on screen size */
        }
        @media (max-width:760px){
            .login{
                width: 100% !important;
            }
        }
        </style>
    </head>
    <body class="w3-light-grey">
        <form class="w3-display-middle w3-card-4 login" action="{% url 'koperasi:login' %}" method="post" enctype="multipart/form-data">
        	<span class="w3-center w3-block"><img src="{% static 'images/icon.png' %}" width='100px;' style="margin-top: 20px"></span>
        	<hr>
            <h3 class="w3-center">Log In</h3>
            {% csrf_token %}
            {% if error_message %}
                <div class="w3-panel w3-pale-red"><p>{{ error_message }}</p></div>
            {% endif %}
                <div class="w3-container w3-padding">
                    <label for="id_username">
                        Username
                    </label>
                    <input id="id_username" maxlength="30" name="username" type="text" class="w3-input w3-border" autofocus>
                </div>

                <div class="w3-container w3-padding">
                    <label for="id_password">
                        Password
                    </label>
                    <input id="id_password" maxlength="30" name="password" type="password" class="w3-input w3-border">
                </div>

                <div class="w3-container w3-padding">
                <button type="submit" class="w3-button w3-green">Submit</button>
                <p>
                    Belum punya akun? <a href="{% url 'koperasi:register' %}">Klik disini</a> untuk mendaftar.
                </p>
                </div>
        </form>
    </body>
</html>

koperasi/templates/koperasi/register.html
{% extends 'base_page.html' %}
{% block title %}Register{%endblock%}
{% block style %}
<style type="text/css">
/* Modal Content/Box */
.register {
	background-color: #fefefe;
	margin:auto auto auto auto; /* 5% from the top, 15% from the bottom and centered */
	width: 40%; /* Could be more or less, depending on screen size */
}

@media (min-width:768px) {
    .register{
        margin-top: 5% !important;
		margin-bottom: 5%;
    }
}
@media (max-width:760px){
    .register{
        width: 100% !important;
    }
}
@media (min-width:375px) {
    .register{
        margin-top: 10%;
    }
}
</style>
{%endblock%}
{% block content %}
<form class="w3-card-4 w3-light-grey w3-padding-large register" action="{% url 'koperasi:register' %}" method="post">
  <h3>Register</h3>
    {% csrf_token %}
	{% if error_message %}
		<div class="w3-panel w3-pale-red"><p>{{ error_message }}</p></div>
	{% endif %}
	<div class="w3-container w3-padding">
		  <label for="id_username">Username:</label>
		  <input id="id_username" maxlength="30" name="username" type="text" class="w3-input w3-border" autofocus>
	</div>
	<div class="w3-container w3-padding">
		  <label for="id_email">E-mail address:</label>
		  <input id="id_email" maxlength="254" name="email" type="text" class="w3-input w3-border">
	</div>
	<div class="w3-container w3-padding">
	  <label for="id_password">Password:</label>
	  <input id="id_password" maxlength="30" name="password" type="password" class="w3-input w3-border">
	</div>
	<div class="w3-container w3-padding">
      <button type="submit" class="w3-button w3-green">Submit</button>
	  <p>
		  Sudah memiliki akun? <a href="{% url 'koperasi:login' %}">Klik disini</a> untuk login.
	  </p>
	</div>
</form>
{%endblock%}