balasjasa/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include('koperasi.urls')),
    path('admin', admin.site.urls),
]
urlpatterns += staticfiles_urlpatterns()

koperasi/urls.py
from django.conf.urls import url
from . import views


app_name = 'koperasi'


urlpatterns = [
    url(r'^$', views.index, name='main'),
    url(r'^akun/add/$', views.AkunCreate, name='akun-add'),
    url(r'^akun/(?P<akun_id>[0-9]+)/delete/$', views.hapus_akun, name='hapus-akun'),
    url(r'^akun/(?P<akun_id>[0-9]+)/$', views.detail_akun, name='detail-akun'),
    url(r'^dashboard', views.dashboard, name='dashboard'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^register$', views.register, name='register'),
    url(r'^buat-koperasi$', views.create_koperasi, name='buat-koperasi'),
]

koperasi/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import datetime


class Koperasi(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nama = models.CharField(max_length=200, verbose_name="nama koperasi")
    badan_hukum = models.CharField(max_length=200, verbose_name="nomor badan hukum")
    telp = models.CharField(max_length=20)
    alamat = models.CharField(max_length=250)
    fax = models.CharField(max_length=50)
    tgl = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return str(self.pk) + " " + self.nama + " " + self.badan_hukum


class Membership(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl_daftar = models.DateField()
    tgl_berakhir = models.DateField()
    masa_aktif = models.IntegerField()
    status = models.BooleanField()

    def __str__(self):
        return " Koperasi: " + self.koperasi.nama + " Tgl daftar: " + str(self.tgl_daftar) + " Tgl berakhir:" + str(self.tgl_berakhir)

# TODO: ManyToMany - Koperasi memiliki banyak AkunPerkiraan


class Login(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)


class AkunPerkiraan(models.Model):
    KATEGORI = (('1', 'Aktiva'), ('2', 'Hutang'), ('3', 'Modal'), ('4', 'Pendapatan'), ('5', 'HPP'), ('6', 'Biaya'))
    SALDO_NORMAL = (('D', 'Debet'), ('K', 'Kredit'))
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    nama = models.CharField(max_length=100)
    kode_akun = models.CharField(max_length=50)
    saldo_normal = models.CharField(max_length=10, choices=SALDO_NORMAL)
    kategori = models.CharField(max_length=1, choices=KATEGORI)

    def __str__(self):
        return self.kategori + "." + self.kode_akun + " - " + self.nama + " - " + self.koperasi

    def get_absolute_url(self):
        return reverse('koperasi:detail-akun', kwargs={'pk': self.pk})


class Anggota(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    JK = (('L', 'Laki-laki'), ('P', 'Perempuan'))
    no_identitas = models.CharField(max_length=50)
    nama = models.CharField(max_length=250)
    jk = models.CharField(max_length=1, choices=JK)
    tempat_lahir = models.CharField(max_length=100, verbose_name='tempat lahir')
    tgl_lahir = models.DateField(verbose_name='tanggal lahir')
    alamat = models.CharField(max_length=300)
    pekerjaan = models.CharField(max_length=100)
    jabatan = models.CharField(max_length=100)
    pic = models.FileField(verbose_name='foto')
    scan_identitas = models.FileField()


class TransaksiSimpan(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl = models.DateTimeField(verbose_name='tanggal')
    jumlah = models.IntegerField()
    keterangan = models.CharField(max_length=200)
    anggota = models.ForeignKey(Anggota, on_delete=models.CASCADE)


class TransaksiPinjam(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl = models.DateTimeField(verbose_name='tanggal')
    jumlah = models.IntegerField()
    keterangan = models.CharField(max_length=200)
    anggota = models.ForeignKey(Anggota, on_delete=models.CASCADE)


class Transaksi(models.Model):
    koperasi = models.ForeignKey(Koperasi, on_delete=models.CASCADE)
    tgl = models.DateTimeField(verbose_name='tanggal')
    dari_akun = models.CharField(max_length=100)
    untuk_akun = models.CharField(max_length=100)
    jumlah = models.IntegerField()
    user = models.CharField(max_length=100)

koperasi/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import AkunPerkiraan, Koperasi


class AkunForm(forms.ModelForm):
    attrs = {'class': 'w3-input w3-border'}
    KATEGORI = (('1', 'Aktiva'), ('2', 'Hutang'), ('3', 'Modal'), ('4', 'Pendapatan'), ('5', 'HPP'), ('6', 'Biaya'))
    SALDO_NORMAL = (('D', 'Debet'), ('K', 'Kredit'))
    attr = attrs
    attr['required'] = True
    attr['autofocus'] = 'True'
    nama = forms.CharField(widget=forms.TextInput(attr))
    kode_akun = forms.CharField(widget=forms.TextInput(attrs))
    saldo_normal = forms.CharField(widget=forms.Select(attrs, choices=SALDO_NORMAL))
    kategori = forms.CharField(widget=forms.Select(attrs, choices=KATEGORI))

    class Meta:
        model = AkunPerkiraan
        fields = ['nama', 'kode_akun', 'saldo_normal', 'kategori']


class KoperasiForm(forms.ModelForm):
    attrs = {'class': 'w3-input w3-border'}
    nama = forms.CharField(widget=forms.TextInput(attrs={'required': True, 'autofocus': True, 'class': 'w3-input w3-border', }))
    badan_hukum = forms.CharField(widget=forms.TextInput(attrs))
    telp = forms.CharField(widget=forms.TextInput(attrs))
    alamat = forms.CharField(widget=forms.TextInput(attrs))
    fax = forms.CharField(widget=forms.TextInput(attrs))
    tgl = forms.DateTimeField(widget=forms.DateTimeInput(attrs))

    class Meta:
        model = Koperasi
        fields = ['nama', 'badan_hukum', 'telp', 'alamat', 'fax', 'tgl']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

koperasi/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
# from django.views import generic
from .models import AkunPerkiraan, Koperasi, Membership
from .forms import UserForm, AkunForm, KoperasiForm
import datetime
from django.forms import modelformset_factory


def index(request):
    return render(request, 'koperasi/index.html')


def dashboard(request):
    if not request.user.is_authenticated:
        return render(request, 'koperasi/login.html')
    else:
        k = Koperasi.objects.filter(user=request.user)
        context = {
            'all_koperasi': k,
            'all_akun': AkunPerkiraan.objects.filter(koperasi=k),
        }
        return render(request, 'koperasi/dashboard.html', context)


def detail_akun(request, akun_id):
    if not request.user.is_authenticated:
        return render(request, 'koperasi/login.html')
    else:
        akun = get_object_or_404(AkunPerkiraan, pk=akun_id)
        context = {
            'akunperkiraan': akun,
        }
        return render(request, 'koperasi/detail.html', context)


def hapus_akun(request, akun_id):
    if not request.user.is_authenticated:
        return render(request, 'koperasi/login.html')
    else:
        akun = AkunPerkiraan.objects.get(pk=akun_id)
        akun.delete()
        k = Koperasi.objects.filter(user=request.user)
        context = {
            'all_koperasi': k,
            'all_akun': AkunPerkiraan.objects.filter(koperasi=k),
        }
        return render(request, 'koperasi/dashboard.html', context)


def register(request):
    form = UserForm(request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                all_koperasi = Koperasi.objects.filter(user=request.user)
                return render(request, 'koperasi/dashboard.html', {'all_koperasi': all_koperasi})
    else:
        context = {
            "form": form,
            'error_message': 'Form is not valid'
        }
        return render(request, 'koperasi/register.html', context)

    context = {
        "form": form,
    }
    return render(request, 'koperasi/register.html', context)


def create_koperasi(request):
    KoperasiFormSet = modelformset_factory(Koperasi, form=KoperasiForm, fields='__all__')
    if request.method == 'POST':
        data = {'form-TOTAL_FORMS': '1', 'form-INITIAL_FORMS': '0', 'form-0-tgl': datetime.date.today()}
        form = KoperasiFormSet(request.POST, data)
        if form.is_valid():
            koperasi = form.save(commit=False)
            koperasi.user = request.user
            koperasi.save()
            m = Membership(koperasi=koperasi, tgl_daftar="2018-01-12", tgl_berakhir="2019-11-12", masa_aktif="12", status=True)
            m.save()
            return render(request, 'koperasi/dashboard.html', {'koperasi': koperasi})
    else:
        data = {'form-TOTAL_FORMS': '1', 'form-INITIAL_FORMS': '0', 'form-0-tgl': datetime.date.today(), 'form-0-DELETE': 'on', }
        form = KoperasiFormSet(data, initial=[{'tgl': datetime.date.today()}])
    context = {'form': form}
    return render(request, 'koperasi/create_koperasi.html', context)


def login_user(request):
    # lakukan pengecekan apakah user sudah di autentikasi, jika sudah arahkan ke halaman dashboard, jika belum lakukan pengecekan user
    if request.user.is_authenticated:
        k = Koperasi.objects.filter(user=request.user)
        context = {
            'all_koperasi': k,
            'all_akun': AkunPerkiraan.objects.filter(koperasi=k.first()),
            'user': request.user
        }
        return render(request, 'koperasi/dashboard.html', context)
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                k = Koperasi.objects.filter(user=request.user)
                context = {
                    'all_koperasi': k,
                    'all_akun': AkunPerkiraan.objects.filter(koperasi=k.first()),
                    'user': request.user
                }
                return render(request, 'koperasi/dashboard.html', context)
            else:
                return render(request, 'koperasi/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'koperasi/login.html', {'error_message': 'Invalid login'})
    return render(request, 'koperasi/login.html')


def logout_user(request):
    logout(request)  # logout auth user
    form = UserForm(request.POST or None)  # mengambil forms dari daftar form
    context = {
        "form": form,
    }
    return render(request, 'koperasi/login.html', context)


def AkunCreate(request):
    form = AkunForm(request.POST or None)
    if form.is_valid():
        akunperkiraan = form.save(commit=False)
        akunperkiraan.koperasi = Koperasi.objects.get(user=request.user)
        akunperkiraan.save()
        return render(request, 'koperasi/detail.html', {'akunperkiraan': akunperkiraan})
    context = {
        "form": form,
    }
    return render(request, 'koperasi/create_akun.html', context)

koperasi/templates/base.html
{% load staticfiles %}
<!--TODO: Benahi halaman dashboard-->
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{%  static 'images/icon.png' %}"/>
	<title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'w3.css' %}">
    <link rel="stylesheet" href="{% static 'theme-green.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
<!-- Navbar -->
<div class="w3-top w3-theme" style="z-index:4">
 <div class="w3-bar w3-theme-d2 w3-left-align w3-large">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="w3_open()"><i class="fa fa-bars"></i></a>
  <a href="{% url 'koperasi:main' %}" class="w3-bar-item w3-button w3-padding-large w3-theme-d4" style="width:220px"><i class="fa fa-home w3-margin-right"></i>Balasjasa.id</a>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-globe"></i></a>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Account Settings"><i class="fa fa-user"></i></a>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-envelope"></i></a>
  <!-- Notifications: style can be found in dropdown.less -->
  <div class="w3-dropdown-hover w3-hide-small">
  </div>
  <a href="#" class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white" title="My Account"><img src="{% static 'photo.jpg' %}" class="w3-circle" style="height:25px;width:25px" alt="Avatar"></a>
 </div>
</div>

<!-- Navbar on small screens -->
<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
  <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
  <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
  <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
  <a href="#" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-animate-left w3-dark-gray" style="z-index:3;width:220px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="{% static 'photo.jpg' %}" class="w3-circle w3-margin-right" style="width:46px">
    </div>
    <div class="w3-col s8 w3-bar">
      <span><strong>{{ user.username }}</strong></span><br>
      <a href="{% url 'koperasi:logout' %}" class="w3-bar-item w3-button" title="Keluar Aplikasi"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
      <a href="#" class="w3-bar-item w3-button"><i class="fa fa-cog"></i></a>
    </div>
  </div>
  <hr>
  <div class="w3-bar-block">
    <h5><a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-dashboard"></i>   Dashboard</a></h5>
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-dark-grey w3-hide-large  w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="#" class="w3-bar-item w3-button w3-padding {% block simpan_aktive %}{% endblock %}"><i class="fa fa-users fa-fw"></i>  Transaksi simpanan</a>
    <a href="#" class="w3-bar-item w3-button w3-padding {% block transaksi_aktive %}{% endblock %}"><i class="fa fa-eye fa-fw"></i>  Transaksi Kas</a>
    <a href="{% url 'koperasi:dashboard' %}" class="w3-bar-item w3-button w3-padding {% block koperasi_aktive %}{% endblock %}"><i class="fa fa-users fa-fw"></i>  Koperasi</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bullseye fa-fw"></i>  Geo</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-diamond fa-fw"></i>  Orders</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bell fa-fw"></i>  News</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-bank fa-fw"></i>  General</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  History</a>
    <a href="#" class="w3-bar-item w3-button w3-padding"><i class="fa fa-cog fa-fw"></i>  Settings</a><br><br>
    <a href="{% url 'koperasi:logout' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-history fa-fw"></i>  Logout</a>
  </div>
</nav>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-main" style="margin-left:220px;margin-top:43px;">
    <header class="w3-container w3-padding-top">
        <h3><b><i class="fa fa-dashboard"></i> Judul halaman</b></h3>
    </header>
    <div class="w3-container">
        {% block content %} {% endblock %}
    </div>
    <!-- Footer -->
    <hr>
    <footer class="w3-container w3-padding w3-light-grey">
        <p>&copy;Copyright. All right reserved <a href="https://www.balasjasa.id/" target="_blank">Balasjasa.id</a></p>
    </footer>
    <!-- End page content -->
</div>
<script>
// Get the Sidebar
var mySidebar = document.getElementById("mySidebar");

// Get the DIV with overlay effect
var overlayBg = document.getElementById("myOverlay");

// Toggle between showing and hiding the sidebar, and add overlay effect
function w3_open() {
    if (mySidebar.style.display === 'block') {
        mySidebar.style.display = 'none';
        overlayBg.style.display = "none";
    } else {
        mySidebar.style.display = 'block';
        overlayBg.style.display = "block";
    }
}

// Close the sidebar with the close button
function w3_close() {
    mySidebar.style.display = "none";
    overlayBg.style.display = "none";
}

function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

<!-- !PAGE CONTENT! -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>
</body>
</html>

koperasi/templates/base_page.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="shortcut icon" type="image/png" href="{%  static 'images/icon.png' %}"/>
        <title>{% block title %}{% endblock %}</title>
        {% block style %}{% endblock %}
        <link rel="stylesheet" href="{% static 'w3.css' %}">
        <link rel="stylesheet" href="{% static 'theme-green.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body class="w3-light-grey">
        <!-- Navbar -->
        <div class="w3-top w3-theme-d2" style="z-index:4">
         <div class="w3-bar w3-left-align w3-large">
              <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="myFunction()"><i class="fa fa-bars"></i></a>
              <a href="{% url 'koperasi:main' %}" class="w3-bar-item w3-button w3-padding-large" style="width:220px"><i class="fa fa-home w3-margin-right"></i>Balasjasa.id</a>
              <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-globe"></i></a>
              <a href="#" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Account Settings"><i class="fa fa-user"></i></a>
              <div class="w3-dropdown-hover w3-hide-small">
                <button class="w3-button w3-padding-large" title="Notifications"><i class="fa fa-bell"></i><span class="w3-badge w3-right w3-small w3-green">3</span></button>
                <div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
                  <a href="#" class="w3-bar-item w3-button">One new friend request</a>
                  <a href="#" class="w3-bar-item w3-button">John Doe posted on your wall</a>
                  <a href="#" class="w3-bar-item w3-button">Jane likes your post</a>
                </div>
              </div>
              <div class="w3-dropdown-hover w3-hide-small">
              <button class="w3-button"><img src="{% static 'photo.jpg' %}" class="w3-circle" style="height:25px;width:25px" alt="Avatar"></button>
                  <div class="w3-dropdown-content w3-bar-block w3-card-4">
                    <a href="#" class="w3-bar-item w3-button">Link 1</a>
                    <a href="#" class="w3-bar-item w3-button">Link 2</a>
                    <a href="#" class="w3-bar-item w3-button">Link 3</a>
                  </div>
              </div>
         </div>
        </div>

        <!-- Navbar on small screens -->
        <div id="nav" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
          <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 1</a>
          <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 2</a>
          <a href="#" class="w3-bar-item w3-button w3-padding-large">Link 3</a>
          <a href="#" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
        </div>

        <div class="w3-main" style="margin-top:43px;">
            <div class="w3-container">

            {% block content %} {% endblock %}
        </div>
        </div>
        <!-- Footer -->
        <footer class="w3-container w3-padding w3-light-grey">
            <p>&copy;Copyright. All right reserved <a href="https://www.balasjasa.id/" target="_blank">Balasjasa.id</a></p>
        </footer>
        <!-- End page content -->
        <script>

        function myFunction() {
            var x = document.getElementById("nav");
            if (x.className.indexOf("w3-show") == -1) {
                x.className += " w3-show";
            } else {
                x.className = x.className.replace(" w3-show", "");
            }
        }
        </script>
    </body>
</html>